---
title: "worm plotting total site biomass"
author: "Sara DeLaurentis"
date: "1/15/2022"
output: html_document
purpose: create summarized worm data, take mean biomass of 3 reps at each site, calculate SD and SE, plot
related files: worm_plotting_20211027.Rmd
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(tidyverse)
library(glue)
library(stringr)
library(stringi)
library(magrittr)
library(dplyr)
library(wesanderson)
library(viridis)
library(ggplot2)

#install.packages("viridis")

#install.packages("wesanderson")


getwd()

```
First need to summarize sums by replicate, then take the mean of the group.
Created summarized df, divided biomass totals by the worm ring area to get the biomass totals for each rep.

```{r }
#setwd("C:/Users/sbaue/coding/R_TEMPRY/Itasca_project_19-21")


#worms <- read.csv("../ItascaEarthwormData_2019.csv")
worms <- read.csv("../Itasca_worms_2021.csv")

```

## FOR 2021 WORMS ONLY ##

```{r}

worms <- worms %>% 
  mutate(rep = case_when(
    grepl("W1", site_name) ~ "W1",
    grepl("W2", site_name) ~ "W2",
    grepl("W3", site_name) ~ "W3"), .after = "site"
  )

worms <- worms %>% 
  mutate(layer = case_when(
    grepl("min", site_name) ~ "min",
    grepl("mus", site_name) ~ "min",
    grepl("org", site_name) ~ "org",), .after = "rep"
  )

view(worms)

#Need to select only organic horizon and mustard-extracted.

worms.org.musEX <- worms %>% 
  filter((grepl("org", site_name)) | (grepl("musEx", site_name)))

worms.org.musEX

#summarize


```

```{r }

#For ecogroup plot (total):
#worm_rep_ecogrp <- worms %>% 
#  group_by(site, ecol_group) %>% 
#  summarise(biomass_AFDg_TOT = sum(biomass_AFDg))
   
#worm_rep_ecogrp %<>% 
#  mutate(biomass_m2 = biomass_AFDg_TOT/0.080425)


worm_rep_sum <-  
 worms.org.musEX %>% 
 group_by(site, rep) %>% 
 mutate(biomass_AFDg_TOT = sum(biomass_AFDg)) %>% 
 ungroup() %>% 
 distinct(site_name, .keep_all = TRUE)
  
worm_rep_sum <- worm_rep_sum %>% 
  rename("biomass_m2" = "biomass.AFDG.m2")

worm_rep_sum$inv_lvl %<>% as.character()
str(worm_rep_sum)
view(worm_rep_sum)  

#truncate unneeded columns

keeps <- c("site", "rep", "biomass_m2")

worm_rep_sum = worm_rep_sum[keeps]
worm_rep_sum  

#create df to merge all desired site/rep combinations
worm.R.df <- matrix(data = NA, nrow = 24, ncol = 2)
worm.R.df[,1] <- c(rep("C2A", 3), rep("C2B", 3), rep("C5A", 3), rep("C5B", 3), rep("D2A",3), rep("D2B", 3), rep("D5A", 3), rep("D5B", 3))
worm.R.df[,2] <- c("W1", "W2", "W3")
colnames(worm.R.df) <- c("site", "rep")

worm.R.df
#worm.R.ecogroup.df

worm_site_summary <- merge(x = worm.R.df, y = worm_rep_sum, all.x = TRUE) # merge expected values df with collected data.
worm_site_summary[is.na(worm_site_summary)] <- 0 # replace NA values with 0

worm_site_summary


```

Create bar graph comparing biomass_m2 at each site. Error bars represent standard error of the mean


```{r wormplot good}

wormplot.FUN <- function(data){
  Wplot <- ggplot(wormplot.stat, aes(x = site, y = mean, fill = treatment)) +
  scale_fill_viridis(discrete = TRUE) +
  geom_col(position = position_dodge()) +
  geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE),
                width = .2,
                position = position_dodge(.9))
  Wplot <- Wplot + ggtitle("Itasca 2021 Worms") +
    theme(plot.title = element_text(size = rel(1.8), margin = margin(b = 10)))+
    theme(axis.text.x = element_text(size = rel(1.4))) +
    theme(axis.text.y = element_text(size = rel(1.4))) 
  Wplot <- Wplot +
    labs(x= "Site", y = "EW biomass (g/m2)", size = rel(1.8)) +
    theme(axis.title.x = element_text(size = rel(1.5), face = "bold", margin = margin(t = 8)))+
    theme(axis.title.y = element_text(size = rel(1.5), face = "bold", margin = margin(r = 8)))+
    theme(legend.text = element_text(size = rel(1.4))) +
    theme(legend.title = element_text(size = rel(1.4)))
  
 print(Wplot) #print
}

#MAKING OUR INPUTS 
#1. wormplot.stat

wormplot.stat <- worm_site_summary %>% 
group_by(site) %>% 
  mutate(mean = mean(biomass_m2), SD = sd(biomass_m2)) %>% 
  ungroup() %>% 
  mutate(SE = SD/(sqrt(length(SD)))) %>% 
  distinct(site, .keep_all = TRUE)

keeps <- c("site","treatment", "forest_type", "biomass_m2", "mean", "SD", "SE")
wormplot.stat = wormplot.stat[keeps]  

view(wormplot.stat)

print(wormplot.stat)

write.csv(wormplot.stat, "wormplot.stat.2021.csv")


##Run the function

wormplot.FUN(wormplot.stat) 

```
