---
title: "worm_plot_ecolgrp_by_site"
author: "Sara DeLaurentis"
date: "1/15/2022"
output: html_document
related files: worm_plotting_20211027.Rmd, worm_plotting_mean_site_biomass.Rmd
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(tidyverse)
library(glue)
library(stringr)
library(stringi)
library(magrittr)
library(dplyr)
library(wesanderson)
library(viridis)
library(ggplot2)
library(ggpubr)

#install.packages("viridis")

#install.packages("wesanderson")


getwd()

```

##Import data from csv, summarize by site and ecol_group.

```{r }
#setwd("C:/Users/sbaue/coding/R_TEMPRY/Itasca_project_19-21")

worms <- read.csv("../ItascaEarthwormData_2019.csv") #2019
#worms <- read.csv("../Itasca_worms_2021.csv") #2021

#worms

```

## FOR 2021 WORMS ONLY ##

```{r }

worms <- worms %>% 
  mutate(rep = case_when(
    grepl("W1", site_name) ~ "W1",
    grepl("W2", site_name) ~ "W2",
    grepl("W3", site_name) ~ "W3"), .after = "site"
  )

worms <- worms %>% 
  mutate(layer = case_when(
    grepl("min", site_name) ~ "min",
    grepl("mus", site_name) ~ "min",
    grepl("org", site_name) ~ "org",), .after = "rep"
  )

view(worms)

#Need to select only organic horizon and mustard-extracted.

worms.org.musEX <- worms %>% 
  filter((grepl("org", site_name)) | (grepl("musEx", site_name)))

worms.org.musEX


#For ecogroup plot (total):
#worm_rep_ecogrp <- worms %>% 
#  group_by(site, ecol_group) %>% 
#  summarise(biomass_AFDg_TOT = sum(biomass_AFDg))
   
#worm_rep_ecogrp %<>% 
#  mutate(biomass_m2 = biomass_AFDg_TOT/0.080425)

#worm_rep_ecogrp$inv_lvl %<>% as.character()
#str(worm_rep_ecogrp)
#view(worm_rep_ecogrp)

```


```{r }
#For ecogroup plot (site mean):

worm_rep_sum <-
 worms %>% #2019
 #worms.org.musEX %>% #2021
 group_by(site, rep, ecol_group) %>% 
 mutate(biomass_AFDg_TOT = sum(biomass.AFDG.m2)) %>% 
 ungroup() %>% 
 distinct(site, rep, ecol_group, .keep_all = TRUE)
  
worm_rep_sum <- worm_rep_sum %>% 
  rename("biomass_m2" = "biomass_AFDg_TOT")

worm_rep_sum$inv_lvl %<>% as.character()
#(worm_rep_sum)
#view(worm_rep_sum)  

#truncate unneeded columns by only selecting the ones we want.

keeps <- c("site", "rep", "treatment", "forest_type", "inv_lvl", "ecol_group", "biomass_m2")
worm_rep_sum = worm_rep_sum[keeps]
#view(worm_rep_sum)  


#worm_rep_ecogrp %<>%
#  group_by(site, ecol_group) %>% 
#  summarise(biomass_eco_m2 = mean(biomass_m2)) %>% 
#  ungroup()
#worm_rep_ecogrp$inv_lvl %<>% as.character()
#class(worm_rep_ecogrp$inv_lvl)

#str(worm_rep_sum)
#view(worm_rep_sum) 


#create df to merge all desired site/rep combinations
worm.R.ecogroup.df <- matrix(data = NA, nrow = 120, ncol = 6)
worm.R.ecogroup.df[,1] <- c(rep("C2A", 15), rep("C2B", 15), rep("C5A", 15), rep("C5B", 15), rep("D2A", 15), rep("D2B", 15), rep("D5A", 15), rep("D5B", 15))
#worm.R.ecogroup.df[,2] <- c(rep("W1", 5), rep("W2", 5), rep("W3", 5)) #2021
worm.R.ecogroup.df[,2] <- c(rep("R1", 5), rep("R2", 5), rep("R3", 5)) #2019
worm.R.ecogroup.df[,3] <- c("endogeic", "epi-endogeic", "epi-anecic", "epigeic", "epi-endogeic.anecic")
worm.R.ecogroup.df[,4] <- c(rep("C2",30), rep("C5", 30), rep("D2", 30), rep("D5", 30))
worm.R.ecogroup.df[,5] <- c(rep("C",60), rep("D", 60))
worm.R.ecogroup.df[,6] <- c(rep("2", 30), rep("5", 30))

colnames(worm.R.ecogroup.df) <- c("site", "rep", "ecol_group", "treatment", "forest_type", "inv_lvl")

#view(worm.R.ecogroup.df)

col_order <- c("site", "rep", "ecol_group", "treatment", "forest_type", "inv_lvl", "biomass_m2")
worm_rep_sum <- worm_rep_sum[,col_order]

#my_data2 <- my_data[, col_order]

worm_site_summary <- merge(x = worm.R.ecogroup.df, y = worm_rep_sum, all.x = TRUE) # merge expected values df with collected data.
worm_site_summary[is.na(worm_site_summary)] <- 0 # replace NA values with 0

view(worm_site_summary)

```

##Good plotting code for individual year plots.

```{r wormplot good}

wormplot.FUN <- function(data, plot.name, title){ #plot construction, variables and coordinates
  Wplot <- ggplot(wormplot.stat, aes(x = site, y = mean, fill = ecol_group)) +
  #scale_fill_viridis(discrete = TRUE) +
  theme_classic() + #I think this chooses fonts and default sizes?
  scale_fill_manual(values = c("#FFFFFF", 
                               "#CCCCCC", 
                               "#808080", 
                               "#333333", 
                               "#000000"),
                    labels = c("Endogeic", "Anecic", "Epi-endogeic", "Epi-endogeic/anecic", "Epigeic")) + #sets color palette
  geom_col(position = position_dodge(), width = .6, colour = "black", linewidth = 1) +
  #geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE),
  #              linewidth = 1,
  #              width = .2,
  #              position = position_dodge(.9)) +
    scale_y_continuous(limits = c(0,4), expand = c(0,0)) #set scale so that both plots will have the same y-axis.

  #title and axis label(tick mark) sizing  
  Wplot <- Wplot + ggtitle(title) +
    theme(plot.title = element_text(size = rel(2.5), margin = margin(b = 10)))+
    theme(axis.text.x = element_text(size = rel(2.4))) +
    theme(axis.text.y = element_text(size = rel(2.4))) 
  
  #axis titles, legend titles, style, margins and sizing.
  Wplot <- Wplot +
    labs(x= "Site", y = expression(Earthworm~biomass~(g/m^2)), size = rel(2.4), fill = "Ecological Group") +
    theme(axis.title.x = element_text(size = rel(2.1), face = "bold", margin = margin(t = 8)))+
    theme(axis.title.y = element_text(size = rel(2.1), face = "bold", margin = margin(r = 8)))+
    theme(legend.text = element_text(size = rel(1.5))) +
    theme(legend.title = element_text(size = rel(1.7)))
  
  png(file = glue("{plot.name}.png"), width = 1000, height = 600, units = 'px') #Printing graph as png, can choose size of graph here
  print(Wplot)
  dev.off()
  return(Wplot)
  
}

```

##MAKING OUR INPUTS 

#IMPORTANT: Needs to be re-run every time you switch the year!!!

```{r stat summary for worm plot}

wormplot.stat <- worm_site_summary %>% 
group_by(site, ecol_group) %>% 
  mutate(mean = mean(biomass_m2), SD = sd(biomass_m2)) %>% 
  ungroup() %>% 
  mutate(SE = SD/(sqrt(length(SD)))) %>% 
  distinct(site, ecol_group, .keep_all = TRUE) %>% 
  group_by(site)

#keep only needed columns
keeps <- c("site","treatment", "ecol_group", "forest_type", "biomass_m2", "mean", "SD", "SE")
wormplot.stat = wormplot.stat[keeps]  

str(wormplot.stat)
view(wormplot.stat)

#print(wormplot.stat)

#write.csv(wormplot.stat, "wormplot.stat.2021.csv")

```

##Run the function

```{r RUN}

#2019 (Plot A)
#wormplot.FUN(wormplot.stat, "ecol_grp_biomass_2019", "2019")
ecol_grp_biomass_A <- wormplot.FUN(wormplot.stat, "ecol_grp_biomass_2019_test", "2019")

print(ecol_grp_biomass_A)

#2021 (Plot B)
#wormplot.FUN(wormplot.stat, "ecol_grp_biomass_2021", "2021")
ecol_grp_biomass_B <- wormplot.FUN(wormplot.stat, "ecol_grp_biomass_2021_test", "2021")

print(ecol_grp_biomass_B)

```

##Plot combining

```{r plot combine}

#Combining graphs using ggarrange

ecolgroup_combine_plot <- ggarrange(ecol_grp_biomass_A, #first plot (from above)
          ecol_grp_biomass_B, #second plot, identical to the first one except different data, has the x axis label in it because it is the center graph of the arrange
                    #theme(axis.text.y = element_blank(), #removing y axis labels from this graph, I did not want more than one y axis label
                     #axis.ticks.y = element_blank(),
                     #axis.title.y = element_blank() ),
         # wdf_litter_plot + #third plot, identical to the first one with different data
                    #theme(axis.text.y = element_blank(), #removing y axis labels from this graph, I did not want more than one y axis label
                     #axis.ticks.y = element_blank(),
                     #axis.title.y = element_blank()),
          widths = c(0.86, 0.86), #changing widths to be equal
          common.legend = TRUE, legend = "bottom", #shared legend, legend position
          nrow = 2, ncol = 1) #number of rows/columns

png(file = "ecol_grp_combine_plot_V1.png", width = 1000, height = 1000, units = "px") #printing combined graph, can again choose size here
print(ecolgroup_combine_plot)


```


#Original plotting code with wes_palette colors. May need changes if you desire to use it.

```{r }


wormplot.FUN <- function(data){
  Wplot <- ggplot(wormplot.df, aes(x = site, y = biomass_m2, fill = ecol_group)) +
  scale_fill_manual(values = wes_palette("Darjeeling1", n = 4)) +
  geom_col(stat = "identity", position = "dodge", width = 0.6) 
  #geom_errorbar(aes(ymin = mean-SE, ymax = mean+SE),
 #               width = .2,
  #              position = position_dodge(.9))
  Wplot <- Wplot + ggtitle("Itasca 2021 Worms", subtitle = "Mean biomass by site and ecologic group") +
    theme(plot.title = element_text(size = rel(1.8), margin = margin(b = 10)))+
    theme(axis.text.x = element_text(size = rel(1.4))) +
    theme(axis.text.y = element_text(size = rel(1.4))) 
  Wplot <- Wplot +
    labs(x= "Site", y = "EW biomass (g/m2)", size = rel(1.8)) +
    labs(fill = "Ecologic group") +
    theme(axis.title.x = element_text(size = rel(1.5), face = "bold", margin = margin(t = 8)))+
    theme(axis.title.y = element_text(size = rel(1.5), face = "bold", margin = margin(r = 8)))+
    theme(legend.text = element_text(size = rel(1.4))) +
    theme(legend.title = element_text(size = rel(1.4)))
  
 print(Wplot) #print
}

#wormplot.df
wormplot.df <- worm_site_summary
wormplot.FUN(wormplot.df) #run the function

```